DROP TABLE IF EXISTS pokemon;

CREATE TABLE pokemon (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  type1 TEXT NOT NULL,
  type2 TEXT NOT NULL,
  hidden_ab TEXT NOT NULL
);