DROP TABLE IF EXISTS pokemon;
DROP TABLE IF EXISTS holidays;
DROP TABLE IF EXISTS books;
DROP TABLE IF EXISTS cats;
DROP TABLE IF EXISTS videogames;


CREATE TABLE pokemon (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  type1 TEXT NOT NULL,
  type2 TEXT NOT NULL,
  hidden_ab TEXT NOT NULL
);

CREATE TABLE holidays (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  country TEXT NOT NULL,
  lang TEXT NOT NULL,
  capital TEXT NOT NULL
);

CREATE TABLE books (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  author TEXT NOT NULL,
  genre TEXT NOT NULL
);

CREATE TABLE cats (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  age INTEGER NOT NULL,
  breed TEXT NOT NULL
);

CREATE TABLE videogames (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  genre TEXT NOT NULL,
  rating INTEGER NOT NULL
);



